FA.JustBlog/Areas/Admin/Controllers/PostController.cs
using FA.JustBlog.Areas.Admin.Models;
using FA.JustBlog.Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FA.JustBlog.Core.Repositories;
using FA.JustBlog.Core.DTO;
using System.Net;

namespace FA.JustBlog.Areas.Admin.Controllers
{
    public class PostController : Controller
    {
        JustBlogContext db = new JustBlogContext();
        PostRepository postrepo = new PostRepository();

        // GET: Admin/Post/Create
        public ActionResult Index()
        {
            var posts = db.Posts.ToList();
            return View(posts);
        }

        public ActionResult Create()
        {
            return View();
        }



        //[Route("Details/{id}")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Single(x => x.Id == id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        [ChildActionOnly]
        public ActionResult LatestViews()
        {
            var posts = db.Posts.OrderByDescending(p => p.PostedOn).Take(5).ToList();
            if (posts == null)
            {
                return HttpNotFound();
            }
            return PartialView("_LatestPosts", posts);
        }

        [ChildActionOnly]
        public ActionResult MostViewedPosts()
        {
            var posts = db.Posts.OrderByDescending(p => p.ViewCount).Take(5).ToList();
            if (posts == null)
            {
                return HttpNotFound();
            }
            return PartialView("_MostViewedPosts", posts);
        }



        [ChildActionOnly]
        public ActionResult MostInterestingPosts()
        {
            //var listPost = new List<Post>();
            var posts = postrepo.GetHighestPost(3);
            if (posts == null)
            {
                return HttpNotFound();
            }
            return PartialView("_MostInterestingPosts", posts);
        }

        [ChildActionOnly]
        public ActionResult PublishedPosts()
        {
            var posts = db.Posts.Where(p => p.Published <= DateTime.Now).ToList();
            if (posts == null)
            {
                return HttpNotFound();
            }
            return PartialView("_PublishedPosts", posts);
        }

        [ChildActionOnly]
        public ActionResult UnpublishedPosts()
        {
            var posts = db.Posts.Where(p => p.Published > DateTime.Now).ToList();
            if (posts == null)
            {
                return HttpNotFound();
            }
            return PartialView("_UnpublishedPosts", posts);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post p)
        {
            if (ModelState.IsValid)
            {
                db.Posts.Add(p);
                db.SaveChanges();
                ModelState.Clear();
                //p = null;
            }
            return View(p);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var post = db.Posts.Where(x => x.Id == id).FirstOrDefault();
            return View(post);
        }

        [HttpPost]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                if(post.Id > 0)
                {
                    var p = db.Posts.Where(x => x.Id == post.Id).FirstOrDefault();
                    if(p != null)
                    {
                        p.Title = post.Title;
                        p.ShortDescription = post.ShortDescription;
                        p.PostContent = post.PostContent;
                        p.Meta = post.Meta;
                        p.UrlSlug = post.UrlSlug;
                        //p.Published = post.Published;
                        //p.PostedOn = post.PostedOn;
                        //p.Modified = post.Modified;
                        //p.CategoryId = post.CategoryId;
                        //p.ViewCount = post.ViewCount;
                        //p.RateCount = post.RateCount;
                        //p.TotalRate = post.TotalRate;
                    }
                }
                else
                {
                    return Content("No data found!");
                }
                db.SaveChanges();
            }
            return View(post);
        }

        public ActionResult Delete(int id)
        {
            var del = db.Posts.Where(x => x.Id == id).FirstOrDefault();
            if (del!= null && del.Id > 0)
            {
                db.Posts.Remove(del);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

FA.JustBlog/Controllers/EntityController.cs
using FA.JustBlog.Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FA.JustBlog.Controllers
{
    public class EntityController : Controller
    {
        private JustBlogContext db = new JustBlogContext();
        // GET: Entity
        public ActionResult Index()
        {
            var posts = db.Posts.ToList();
            return View(posts);
        }
        public ActionResult Entity()
        {
            var posts = db.Posts.ToList();
            return View(posts);
        }
    }
}

FA.JustBlog/Controllers/PostController.cs
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Repositories;
using FA.JustBlog.Models;
using IdentitySample.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
namespace FA.JustBlog.Controllers
{
    public class PostController : Controller
    {
        private JustBlogContext db = new JustBlogContext();
        private PostRepository data = new PostRepository();

        // GET: Post/Index
        public ActionResult Index()
        {
            var posts = db.Posts.ToList();
            return View(posts);
        }

        public ActionResult LatestPosts()
        {
            var posts = db.Posts.OrderByDescending(p => p.PostedOn).ToList();
            return PartialView("LatestPosts", posts);
        }

        //[Route("Post/released/{year}/{month}/{title}")]
        public ActionResult Details(int year,int month,string title)
        {
            var post = data.Find(year, month, title);
            if (post != null && post.Id > 0)
            {
                ViewBag.Titles = "Test Router";
                return View(post);
            }
            return View();
        }

        [ChildActionOnly]
        public ActionResult MostViews()
        {
            var post = db.Posts.OrderByDescending(p => p.ViewCount).Take(5).ToList();
            if (post == null)
            {
                return HttpNotFound();
            }
            return PartialView("_ListPosts", post);
        }
        [ChildActionOnly]
        public ActionResult LatestViews()
        {
            var post = db.Posts.OrderByDescending(p => p.PostedOn).Take(5).ToList();
            if (post == null)
            {
                return HttpNotFound();
            }
            return PartialView("_LatestPosts", post);
        }
        public ActionResult PopularTags()
        {
            var post = db.Tags.OrderByDescending(p => p.Count).Take(10).ToList();
            if (post == null)
            {
                return HttpNotFound();
            }
            return PartialView("_PopularTags", post);
        }
        public ActionResult AllCategory()
        {
            var posts = db.Categories.ToList();
            return PartialView("_Category", posts);
        }
    }
}

FA.JustBlog/Views/Shared/PostPartial.cshtml
@model IEnumerable<FA.JustBlog.Core.Models.Post>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShortDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostContent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Meta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UrlSlug)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Published)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Modified)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ViewCount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RateCount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalRate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TagValues)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShortDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostContent)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Meta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UrlSlug)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Published)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostedOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Modified)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ViewCount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RateCount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalRate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TagValues)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

FA.JustBlog/Views/Shared/PostView.cshtml
@{
    Layout = null;
    ViewBag.Title = "Posts";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title</title>
    <link rel="icon" type="image/x-icon" href="~/Content/PostPage/assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/Content/PostPage/css/styles.css" rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="index.html">Start Bootstrap</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">Home</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">About</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">Sample Post</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Header-->
    <header class="masthead" style="background-image: url('../../Content/PostPage/assets/img/home-bg.jpg')
    ">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Clean Blog</h1>
                        <span class="subheading">A Blog Theme by Start Bootstrap</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        @RenderBody()
    </div>
    <hr />
    <!-- Footer-->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/Content/PostPage/js/scripts.js"></script>
</body>
</html>

FA.JustBlog/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

FA.JustBlog/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

FA.JustBlog/Views/Shared/_Layout.cshtml
@Html.Partial("_PartialHeader")

@RenderBody()

@Html.Partial("_PartialFooter")

FA.JustBlog/Views/Shared/_Layout0.cshtml
< !DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Just Blog</title>
    <link rel="icon" type="image/x-icon" href="~/Content/assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/Content/css/styles.css" rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="index.html">Just Blog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Header-->
    <header class="masthead" style="background-image: url('../Content/assets/img/home-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Just Blog</h1>
                        <span class="subheading">A Blog Theme by Start Bootstrap</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-9 mx-auto">
                <!-- Main Content-->
                <div class="container px-4 px-lg-5">
                    <div class="row gx-4 gx-lg-5 justify-content-center">
                        <div class="col-md-10 col-lg-8 col-xl-7">
                            <!-- Post preview-->
                            <div class="post-preview">
                                @foreach (var item in Model)
                                {
                                    <a href="Details/@item.Id">
                                        <h2 class="post-title">@item.Title</h2>
                                        <h3 class="post-subtitle">@Html.DisplayFor(modelItem => item.ShortDescription)</h3>
                                    </a>
                                    <p class="post-meta">
                                        Posted on @Html.DisplayFor(modelItem => item.PostedOn)
                                    </p>
                                    <!-- Divider-->
                                    <hr class="my-4" />
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 mx-auto">
                @Html.Action("AboutCard", "Post")
            </div>
        </div>
    </div>





    @Html.Partial("_PartialFooter")

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/Content/js/scripts.js"></script>
</body>
</html>

FA.JustBlog/Views/Shared/_PartialFooter.cshtml
<!-- Footer-->
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!-- Core theme JS-->
<script src="@Url.Content("~/Content/js/scripts.js")"></script>
</body>
</html>

FA.JustBlog/Views/Shared/_PartialHeader.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title</title>
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@

    <link rel="icon" type="image/x-icon" href="@Url.Content("~/Content/assets/favicon.ico")" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="@Url.Content("~/Content/css/styles.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            @Html.ActionLink("Just Blog", "Index", "Home", null, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link px-lg-3 py-3 py-lg-4" })</li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">About</a></li>
                    <li class="nav-item">@Html.ActionLink("Entity Framework", "Index", "Entity", null, new { @class = "nav-link px-lg-3 py-3 py-lg-4" })</li>
                    <li class="nav-item">@Html.ActionLink("MVC", "Index", "MVC", null, new { @class = "nav-link px-lg-3 py-3 py-lg-4" })</li>
                    <li class="nav-item">@Html.ActionLink("Post", "Index", "Post", null, new { @class = "nav-link px-lg-3 py-3 py-lg-4" })</li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4 href=" #"">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Header-->
    <header class="masthead" style="background-image: url('../../Content/assets/img/home-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Just Blog</h1>
                        <span class="subheading">A Blog Theme by Start Bootstrap</span>
                    </div>
                </div>
            </div>
        </div>
    </header>